### ISSUE TITLE
A&M&T Evaporator Crash

### ISSUE THREAD

**Issue by ShadowXx** [Haggle1996/RevolutionPack#14]
Upon opening gui of an Evaporator from Apple milk and tea it crashes client back to desktop,

java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:29)
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:59)
	at mods.defeatedcrow.common.tile.appliance.TileEvaporator.getGuiFluidUpdate(TileEvaporator.java:152)
	at mods.defeatedcrow.common.tile.appliance.ContainerEvaporator.func_75137_b(ContainerEvaporator.java:147)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26)
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Haggle1996** [comment]
This will be fixed in the next update -- AMT wasn't handling the new forge fluid update, but now a fix has been released.
