### ISSUE TITLE
Crash Laser of secutity craft

### ISSUE THREAD

**Issue by taze57050** [Haggle1996/RevolutionPack#163]
20:14:56] [Server thread/ERROR]: Encountered an unexpected exception

net.minecraft.util.ReportedException: Ticking block entity

	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]

	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]

	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]

	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

Caused by: java.lang.ClassCastException: ZombieAwareness.EntityScent cannot be cast to net.minecraft.entity.player.EntityPlayer

	at net.geforcemods.securitycraft.tileentity.TileEntityLogger.attackEntity(TileEntityLogger.java:15) ~[TileEntityLogger.class:?]

	at net.geforcemods.securitycraft.api.TileEntitySCTE.func_145845_h(TileEntitySCTE.java:102) ~[TileEntitySCTE.class:?]

	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]

	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]

	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]

	... 4 more

**Comment by taze57050** [comment]
is conflict between zombie awareness and securitycraft , i disabled zombie awareness , and serv not crashed

**Comment by Haggle1996** [comment]
EntityScent is turned off in the configs -- you may just need to reinstall the pack, though the pack is completely playable (though slightly easier) without Zombie Awareness.

**Comment by Haggle1996** [comment]
I had typed a longer explanation, but it got eaten by Internet squirrels. Basically, this error occurs when you add/remove entity-adding mods from an existing world.
