### ISSUE TITLE
Crash with keypad securitycraft

### ISSUE THREAD

**Issue by taze57050** [Haggle1996/RevolutionPack#165]
Crash with tape code in keypad : 

[21:32:38] [Server thread/ERROR]: Encountered an unexpected exception

net.minecraft.util.ReportedException: Ticking block entity

	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]

	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]

	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]

	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

Caused by: java.lang.ClassCastException: net.minecraft.entity.monster.EntityCreeper cannot be cast to net.minecraft.entity.player.EntityPlayer

	at net.geforcemods.securitycraft.tileentity.TileEntityLogger.attackEntity(TileEntityLogger.java:15) ~[TileEntityLogger.class:?]

	at net.geforcemods.securitycraft.api.TileEntitySCTE.func_145845_h(TileEntitySCTE.java:102) ~[TileEntitySCTE.class:?]

	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]

	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]

	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]

**Comment by NachtRaben** [comment]
Please provide us the full logs for sanity sake.

**Comment by Haggle1996** [comment]
Duplicate of #164. The entity list saved is mismatched with the mod list.
