### ISSUE TITLE
Crash client Reactorcraft block

### ISSUE THREAD

**Issue by taze57050** [Haggle1996/RevolutionPack#166]
In my mountain , reactorcraft generate a machine block in missing texture , i right click in this block and my game crashed : 

[06/1/2016 20:25:06 PM] [20:25:06] [Client thread/FATAL]: Unreported exception thrown!
[06/1/2016 20:25:06 PM] java.lang.NullPointerException
[06/1/2016 20:25:06 PM] 	at Reika.DragonAPI.Base.BlockTEBase.func_149727_a(BlockTEBase.java:79) ~[BlockTEBase.class:?]
[06/1/2016 20:25:06 PM] 	at Reika.ReactorCraft.Blocks.BlockReactorTile.func_149727_a(BlockReactorTile.java:201) ~[BlockReactorTile.class:?]
[06/1/2016 20:25:07 PM] 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326) ~[bje.class:?]
[06/1/2016 20:25:07 PM] 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447) ~[bao.class:?]
[06/1/2016 20:25:07 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953) ~[bao.class:?]
[06/1/2016 20:25:07 PM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
[06/1/2016 20:25:08 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[06/1/2016 20:25:09 PM] 	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[06/1/2016 20:25:09 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_66]
[06/1/2016 20:25:10 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[06/1/2016 20:25:11 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66]
[06/1/2016 20:25:11 PM] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66]
[06/1/2016 20:25:11 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[06/1/2016 20:25:11 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[06/1/2016 20:25:11 PM] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
[06/1/2016 20:25:11 PM] // I let you down. Sorry :(
[06/1/2016 20:25:11 PM] 
[06/1/2016 20:25:11 PM] Time: 1/6/16 8:25 PM
[06/1/2016 20:25:11 PM] Description: Unexpected error
[06/1/2016 20:25:11 PM] 
[06/1/2016 20:25:11 PM] java.lang.NullPointerException: Unexpected error
[06/1/2016 20:25:11 PM] 	at Reika.DragonAPI.Base.BlockTEBase.func_149727_a(BlockTEBase.java:79)
[06/1/2016 20:25:11 PM] 	at Reika.ReactorCraft.Blocks.BlockReactorTile.func_149727_a(BlockReactorTile.java:201)
[06/1/2016 20:25:11 PM] 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
[06/1/2016 20:25:11 PM] 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
[06/1/2016 20:25:11 PM] 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
[06/1/2016 20:25:11 PM] 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[06/1/2016 20:25:11 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[06/1/2016 20:25:11 PM] 	at net.minecraft.client.main.Main.main(SourceFile:148)
[06/1/2016 20:25:11 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06/1/2016 20:25:11 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[06/1/2016 20:25:11 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[06/1/2016 20:25:11 PM] 	at java.lang.reflect.Method.invoke(Unknown Source)
[06/1/2016 20:25:11 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[06/1/2016 20:25:11 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[06/1/2016 20:25:11 PM] 
[06/1/2016 20:25:11 PM] 
[06/1/2016 20:25:11 PM] A detailed walkthrough of the error, its code path and all known details is as follows:
[06/1/2016 20:25:11 PM] ---------------------------------------------------------------------------------------
[06/1/2016 20:25:11 PM] 
[06/1/2016 20:25:11 PM] -- Head --
[06/1/2016 20:25:11 PM] Stacktrace:
[06/1/2016 20:25:11 PM] 	at Reika.DragonAPI.Base.BlockTEBase.func_149727_a(BlockTEBase.java:79)
[06/1/2016 20:25:11 PM] 	at Reika.ReactorCraft.Blocks.BlockReactorTile.func_149727_a(BlockReactorTile.java:201)
[06/1/2016 20:25:11 PM] 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:326)
[06/1/2016 20:25:11 PM] 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
[06/1/2016 20:25:11 PM] 
[06/1/2016 20:25:11 PM] -- Affected level --
[06/1/2016 20:25:11 PM] Details:
[06/1/2016 20:25:11 PM] 	Level name: MpServer
[06/1/2016 20:25:11 PM] 	All players: 2 total; [GCEntityClientPlayerMP['**MINECRAFTUSERNAME**'/795706, l='MpServer', x=-263.52, y=84.90, z=-52.06], MCH_ViewEntityDummy['McHeliDummyEntity'/262602, l='MpServer', x=205.50, y=66.62, z=292.50]]
[06/1/2016 20:25:11 PM] 	Chunk stats: MultiplayerChunkCache: 441, 441
[06/1/2016 20:25:11 PM] 	Level seed: 0
[06/1/2016 20:25:11 PM] 	Level generator: ID 04 - RTG, ver 0. Features enabled: false
[06/1/2016 20:25:11 PM] 	Level generator options: 
[06/1/2016 20:25:11 PM] 	Level spawn location: World: (205,64,292), Chunk: (at 13,4,4 in 12,18; contains blocks 192,0,288 to 207,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
[06/1/2016 20:25:11 PM] 	Level time: 5647444 game time, 5659805 day time
[06/1/2016 20:25:11 PM] 	Level dimension: 0
[06/1/2016 20:25:11 PM] 	Level storage version: 0x00000 - Unknown?
[06/1/2016 20:25:11 PM] 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
[06/1/2016 20:25:11 PM] 	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
[06/1/2016 20:25:11 PM] 	Forced entities: 29 total; [EntityBat['Bat'/1131913, l='MpServer', x=-185.25, y=37.00, z=-1.53], EntityVoidMonster['Void Monster'/957331, l='MpServer', x=-256.19, y=-3.00, z=-40.08], EntityCow['Cow'/985261, l='MpServer', x=-190.28, y=69.00, z=-119.06], EntityBat['Bat'/1119417, l='MpServer', x=-329.47, y=51.23, z=-92.06], EntityBat['Bat'/1119418, l='MpServer', x=-331.94, y=51.26, z=-85.59], EntityBat['Bat'/1129790, l='MpServer', x=-268.90, y=15.11, z=-127.53], EntityCow['Cow'/795709, l='MpServer', x=-232.22, y=69.00, z=14.19], EntityCow['Cow'/795710, l='MpServer', x=-212.38, y=69.00, z=-42.56], EntityCow['Cow'/795711, l='MpServer', x=-218.53, y=68.00, z=-31.69], GCEntityClientPlayerMP['**MINECRAFTUSERNAME**'/795706, l='MpServer', x=-263.52, y=84.90, z=-52.06], EntityGib['unknown'/262604, l='MpServer', x=205.85, y=66.28, z=292.50], EntityCow['Cow'/1045063, l='MpServer', x=-233.16, y=69.00, z=13.50], EntityCow['Cow'/795716, l='MpServer', x=-232.28, y=73.00, z=-84.69], EntityGib['unknown'/262605, l='MpServer', x=205.15, y=66.28, z=292.50], EntityCow['Cow'/795712, l='MpServer', x=-204.81, y=68.00, z=12.16], EntityTrail['unknown'/262601, l='MpServer', x=-263.52, y=84.90, z=-52.06], EntityCow['Cow'/795714, l='MpServer', x=-211.84, y=68.00, z=-56.16], MCH_ViewEntityDummy['McHeliDummyEntity'/262602, l='MpServer', x=205.50, y=66.62, z=292.50], EntityCow['Cow'/795715, l='MpServer', x=-213.03, y=68.00, z=-55.47], EntityGib['unknown'/262603, l='MpServer', x=205.50, y=66.50, z=292.50], EntityBat['Bat'/1136964, l='MpServer', x=-265.39, y=47.68, z=-69.78], EntityCow['Cow'/795753, l='MpServer', x=-191.78, y=68.00, z=-120.78], EntityCow['Cow'/795754, l='MpServer', x=-191.50, y=68.00, z=-119.56], EntityCow['Cow'/864490, l='MpServer', x=-213.00, y=68.00, z=-55.47], EntityCow['Cow'/795750, l='MpServer', x=-194.97, y=68.00, z=-122.38], EntityCow['Cow'/795751, l='MpServer', x=-190.28, y=69.00, z=-119.09], EntityBat['Bat'/1124961, l='MpServer', x=-333.10, y=52.02, z=-83.49], EntityBat['Bat'/1130216, l='MpServer', x=-328.92, y=51.55, z=-89.70], EntityBat['Bat'/1130218, l='MpServer', x=-329.43, y=51.62, z=-87.11]]
[06/1/2016 20:25:11 PM] 	Retry entities: 0 total; []
[06/1/2016 20:25:12 PM] 	Server brand: fml,forge
[06/1/2016 20:25:12 PM] 	Server type: Non-integrated multiplayer server
[06/1/2016 20:25:12 PM] Stacktrace:
[06/1/2016 20:25:12 PM] 	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
[06/1/2016 20:25:12 PM] 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
[06/1/2016 20:25:12 PM] 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
[06/1/2016 20:25:12 PM] 	at net.minecraft.client.main.Main.main(SourceFile:148)
[06/1/2016 20:25:12 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[06/1/2016 20:25:12 PM] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[06/1/2016 20:25:12 PM] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[06/1/2016 20:25:12 PM] 	at java.lang.reflect.Method.invoke(Unknown Source)
[06/1/2016 20:25:12 PM] 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[06/1/2016 20:25:12 PM] 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[06/1/2016 20:25:12 PM] 
[06/1/2016 20:25:12 PM] -- System Details --
[06/1/2016 20:25:12 PM] Details:
[06/1/2016 20:25:12 PM] 	Minecraft Version: 1.7.10
[06/1/2016 20:25:12 PM] 	Operating System: Windows 7 (amd64) version 6.1
[06/1/2016 20:25:12 PM] 	Java Version: 1.8.0_66, Oracle Corporation
[06/1/2016 20:25:12 PM] 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
[06/1/2016 20:25:12 PM] 	Memory: 1406433304 bytes (1341 MB) / 3726336000 bytes (3553 MB) up to 4277534720 bytes (4079 MB)
[06/1/2016 20:25:12 PM] 	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms2048M -Xmx4096M -XX:MetaspaceSize=256M
[06/1/2016 20:25:12 PM] 	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
[06/1/2016 20:25:12 PM] 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
[06/1/2016 20:25:12 PM] 	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_C1 199 mods loaded, 199 mods active
[06/1/2016 20:25:12 PM] 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
[06/1/2016 20:25:12 PM] 	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	AppleMilkCore{1.1.0} [AppleMilkCore] (minecraft.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	bettersleepingcore{1.0} [Better Sleeping Core] (minecraft.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	MorePlanetsASM{} [More Planets Core] (minecraft.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	OpenComputers|Core{1.5.21.41} [OpenComputers (Core)] (minecraft.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	OpenModsCore{0.9} [OpenModsCore] (minecraft.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	ExpandedIndustry{11.18.0a} [Expanded Industry] (1.7.10-ExpandedIndustry-11.18.0a.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	CustomOreGen{1.2.24-58-g746bdd1} [Custom Ore Generation] (CustomOreGen-1.7.10-1.2.24-58-g746bdd1.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	HardLib{11.18.0a} [HardLib] (1.7.10-HardLib-11.18.0b.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	HarderOres{11.18.0b} [Harder Ores] (1.7.10-HarderOres-11.18.0b.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	HarderWildlife{11.18.0a} [Harder Wildlife] (1.7.10-HarderWildlife-11.18.0a.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	securitycraft{v1.8.1} [SecurityCraft] ([1.7.10] SecurityCraft v1.8.1.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	Treecapitator{1.7.10} [Treecapitator] ([1.7.10]Treecapitator-universal-2.0.4.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	ae2stuff{0.5.1.60} [AE2 Stuff] (ae2stuff-0.5.1.60-mc1.7.10.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	AgriCraft{1.7.10-1.4.6-hotfix} [AgriCraft] (AgriCraft-1.7.10-1.4.6-hotfix.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	animalsPlus{1.2} [Animals+] (animalsPlus-1.2.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	DCsAppleMilk{1.7.10_2.8o} [Apple&Milk&Tea!] (AppleMilkTea2-1.7.10_2.8o.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	DCsNEIPluginAMT{1.7.10_1.0a} [NEIPluginForAMT] (AppleMilkTea2-1.7.10_2.8o.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	Automagy{0.27} [Automagy] (Automagy-1.7.10-0.27.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.1a2.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1521-universal.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	IC2{2.2.791-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.791-experimental.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	CoFHCore{1.7.10R3.1.0B1} [CoFH Core] (CoFHCore-[1.7.10]3.1.0B1-321.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	Forestry{4.2.2.50} [Forestry for Minecraft] (forestry_1.7.10-4.2.2.50.jar) 
[06/1/2016 20:25:12 PM] 	UCHIJA	HardcoreQuesting{4.4.4} [Hardcore Questing Mode] (HQM-The Journey-4.4.4.jar)

**Comment by Haggle1996** [comment]
Please report this to Reika directly on his issue tracker. 

https://github.com/ReikaKalseki/Reika_Mods_Issues

**Comment by ReikaKalseki** [comment]
If something worldgenned ReC machines, you have a *serious* issue, and not one on my end.

**Comment by DaMachinator** [comment]
So it crashed. The important part is figuring out what mod is generating RoC machines as "ore"

**Comment by NachtRaben** [comment]
If you would kindly upload your entire forge-latest log that would be appreciated.
If you are using any FPS enhancment mods, or mods that modify rendering in any way (eg, optifine) please remove them before sending us the log.

**Comment by NachtRaben** [comment]
[06/1/2016 20:25:12 PM] FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_C1 199 mods loaded, 199 mods active

Please try to reproduce this without optifine.

**Comment by taze57050** [comment]
Is a changement of id because of idfixer

**Comment by ReikaKalseki** [comment]
And this is why I so strongly advise against ID fixing tools.
