### ISSUE TITLE
GalactiCraft error with -30 dimension prevents loading worlds.

### ISSUE THREAD

**Issue by Haggle1996** [Haggle1996/RevolutionPack#203]
Full log: http://paste.atlauncher.com/view/e6e9644c

Galacticraft can't unload dimension -30, so the instance hangs. Retry with GS1.0.6.

[01/2/2016 23:22:02 PM] [Server thread/ERROR] [FML]: A fatal exception occurred during the server about to start event
10935.[01/2/2016 23:22:02 PM] java.lang.IllegalArgumentException: Failed to unregister dimension for id -30; No provider registered
10936.[01/2/2016 23:22:02 PM]         at net.minecraftforge.common.DimensionManager.unregisterDimension(DimensionManager.java:134) ~[DimensionManager.class:?]
10937.[01/2/2016 23:22:02 PM]         at micdoodle8.mods.galacticraft.core.util.WorldUtil.unregisterPlanets(WorldUtil.java:750) ~[WorldUtil.class:?]
10938.[01/2/2016 23:22:02 PM]         at micdoodle8.mods.galacticraft.core.GalacticraftCore.unregisterDims(GalacticraftCore.java:569) ~[GalacticraftCore.class:?]
10939.[01/2/2016 23:22:02 PM]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_71]
10940.[01/2/2016 23:22:02 PM]         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_71]
10941.[01/2/2016 23:22:02 PM]         at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_71]
10942.[01/2/2016 23:22:02 PM]         at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]

**Comment by Haggle1996** [comment]
fixed in 2.1.2.0
