### ISSUE TITLE
Server Crash BiomesoPlenty

### ISSUE THREAD

**Issue by StrayCargo** [Haggle1996/RevolutionPack#246]
Time: 2/12/16 9:38 PM
Description: Exception in server tick loop

java.lang.RuntimeException: Already decorating!!
    at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:106)
    at biomesoplenty.api.biome.BOPInheritedBiome.func_76728_a(BOPInheritedBiome.java:42)
    at rtg.world.biome.realistic.RealisticBiomeBase.rDecorate(RealisticBiomeBase.java:229)
    at rtg.world.gen.ChunkProviderRTG.func_73153_a(ChunkProviderRTG.java:67
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:384)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1165)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
    at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
    at net.minecraftforge.common.util.AsynchronousExecutor

**Comment by NachtRaben** [comment]
This is pretty normal if your server is heavily overloaded, usually rebooting the server will fix it. Try not to excessively generate new terrain as doing so will cause this to happen more frequently.

If it was not an issue with generating terrain then provide us a full log and a description of what you were doing when the crash happened.

**Comment by NachtRaben** [comment]
Also, using mods like optifine will cause this to happen in a modded minecraft instance.

**Comment by StrayCargo** [comment]
ok so i will see if I can get the whole log

**Comment by Haggle1996** [comment]
As NachtRaben said, Already Decorating errors happen on occasion during world gen, particularly in packs with many world-gen affecting mods. They happen when two mods try to decorate the same block simultaneously. I wouldn't worry too much about them unless you crash constantly with this error -- and that usually it means a problematic seed. If that's the case, please post your world seed (by doing /seed and copying from the log), as well as your coordinates, and I can try to diagnose the problem. Closing the issue in the mean time.
