### ISSUE TITLE
Null Point Errors since upgrading to 2400

### ISSUE THREAD

**Issue by devanchya** [Haggle1996/RevolutionPack#319]
Since upgrading to 2400 on Saturday, our logs are getting filled with the following errors.  This is with and with out players on the server 

`[14:40:09] [Server thread/ERROR] [FML/]: Index: 2 Listeners:
[14:40:09] [Server thread/ERROR] [FML/]: 0: NORMAL
[14:40:09] [Server thread/ERROR] [FML/]: 1: ASM: thaumcraft.common.lib.events.EventHandlerWorld@39c6ae89 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 2: ASM: hardcorequesting.EventHandler@42bb3416 onEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 3: ASM: vazkii.botania.common.item.ItemCraftingHalo@7a999c3c onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 4: ASM: vazkii.botania.common.achievement.AchievementTriggerer@1310ca3e onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 5: ASM: mods.railcraft.common.util.crafting.CraftingHandler@e1279f9 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 6: ASM: Reika.RotaryCraft.RotaryEventManager@7d52bd38 cleanUpReservoirCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 7: ASM: pavocado.exoticbirds.init.EBEventHandler@4be6652f crafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 8: ASM: minetweaker.mc1710.FMLEventHandler@e1a8717 onPlayerItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 9: ASM: matteroverdrive.handler.PlayerEventHandler@800bc40 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 10: ASM: pneumaticCraft.common.recipes.CraftingHandler@169db01f onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 11: ASM: com.draco18s.industry.IndustryEventHandler@7120dbfc onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 12: ASM: appeng.core.stats.AchievementCraftingHandler@37a26326 onPlayerCraftingEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 13: ASM: tuhljin.automagy.lib.events.AutomagyEventHandler@673b396f onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 14: ASM: buildcraft.core.AchievementManager@23405207 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 15: ASM: enviromine.handlers.EM_EventManager@720582e6 onCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 16: ASM: enviromine.handlers.crafting.CamelPackRefillHandler@36c4788d onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 17: ASM: enviromine.handlers.crafting.CamelPackIntegrationHandler@3ce6e6e onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 18: ASM: enviromine.handlers.crafting.GaskMaskRefillHandler@4b07c3c onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 19: ASM: enviromine.handlers.crafting.LampLightingHandler@366baf25 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 20: ASM: thaumic.tinkerer.common.item.SpellClothCraftingHandler@4b8eef1f ItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 21: ASM: fox.spiteful.forbidden.FMEventHandler@26474176 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 22: ASM: galaxyspace.SolarSystem.core.achievements.AchEvent@6f3a9711 onCraft(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 23: ASM: com.jaquadro.minecraft.gardentrees.core.handlers.ForgeEventHandler@68eeb408 handleCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 24: ASM: blusunrize.immersiveengineering.common.EventHandler@1b9a4099 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 25: ASM: li.cil.oc.common.EventHandler$@6347d2d1 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 26: ASM: mcjty.rftools.FMLEventHandlers@7552cacc onItemCraftedEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 27: ASM: com.draco18s.ores.OresEventHandler@28c793d1 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/ERROR] [FML/]: 28: ASM: com.draco18s.wildlife.WildlifeEventHandler@77565456 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at hardcorequesting.quests.QuestTaskItemsCrafting.create(QuestTaskItemsCrafting.java:36)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at hardcorequesting.quests.QuestTaskItemsCrafting.onCrafting(QuestTaskItemsCrafting.java:32)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at hardcorequesting.EventHandler.onEvent(EventHandler.java:80)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler_145_EventHandler_onEvent_ItemCraftedEvent.invoke(.dynamic)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:570)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onCrafted(UnitCrafting.java:108)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onCrafting(UnitCrafting.java:91)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onProduction(UnitCrafting.java:524)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.page.unit.Unit.produce(Unit.java:154)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.page.unit.Unit.onUpdate(Unit.java:184)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onUpdate(UnitCrafting.java:265)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.page.PageMain.onUpdate(PageMain.java:51)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.tileentity.TileEntityTable.func_145845_h(TileEntityTable.java:320)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.world.World.func_72939_s(World.java:1939)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[14:40:09] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[14:40:17] [Server thread/ERROR] [FML/]: Exception caught during firing event cpw.mods.fml.common.gameevent.PlayerEvent$ItemCraftedEvent@1caab022:
java.lang.NullPointerException
        at hardcorequesting.quests.QuestTaskItemsCrafting.create(QuestTaskItemsCrafting.java:36) ~[QuestTaskItemsCrafting.class:?]
        at hardcorequesting.quests.QuestTaskItemsCrafting.onCrafting(QuestTaskItemsCrafting.java:32) ~[QuestTaskItemsCrafting.class:?]
        at hardcorequesting.EventHandler.onEvent(EventHandler.java:80) ~[EventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_145_EventHandler_onEvent_ItemCraftedEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:570) ~[FMLCommonHandler.class:?]
        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onCrafted(UnitCrafting.java:108) ~[UnitCrafting.class:?]
        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onCrafting(UnitCrafting.java:91) ~[UnitCrafting.class:?]
        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onProduction(UnitCrafting.java:524) ~[UnitCrafting.class:?]
        at com.ewyboy.ewysworkshop.page.unit.Unit.produce(Unit.java:154) ~[Unit.class:?]
        at com.ewyboy.ewysworkshop.page.unit.Unit.onUpdate(Unit.java:184) ~[Unit.class:?]
        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onUpdate(UnitCrafting.java:265) ~[UnitCrafting.class:?]
        at com.ewyboy.ewysworkshop.page.PageMain.onUpdate(PageMain.java:51) ~[PageMain.class:?]
        at com.ewyboy.ewysworkshop.tileentity.TileEntityTable.func_145845_h(TileEntityTable.java:320) ~[TileEntityTable.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[14:40:17] [Server thread/ERROR] [FML/]: Index: 2 Listeners:
[14:40:17] [Server thread/ERROR] [FML/]: 0: NORMAL
[14:40:17] [Server thread/ERROR] [FML/]: 1: ASM: thaumcraft.common.lib.events.EventHandlerWorld@39c6ae89 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 2: ASM: hardcorequesting.EventHandler@42bb3416 onEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 3: ASM: vazkii.botania.common.item.ItemCraftingHalo@7a999c3c onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 4: ASM: vazkii.botania.common.achievement.AchievementTriggerer@1310ca3e onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 5: ASM: mods.railcraft.common.util.crafting.CraftingHandler@e1279f9 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 6: ASM: Reika.RotaryCraft.RotaryEventManager@7d52bd38 cleanUpReservoirCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 7: ASM: pavocado.exoticbirds.init.EBEventHandler@4be6652f crafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 8: ASM: minetweaker.mc1710.FMLEventHandler@e1a8717 onPlayerItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 9: ASM: matteroverdrive.handler.PlayerEventHandler@800bc40 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 10: ASM: pneumaticCraft.common.recipes.CraftingHandler@169db01f onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 11: ASM: com.draco18s.industry.IndustryEventHandler@7120dbfc onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 12: ASM: appeng.core.stats.AchievementCraftingHandler@37a26326 onPlayerCraftingEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 13: ASM: tuhljin.automagy.lib.events.AutomagyEventHandler@673b396f onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 14: ASM: buildcraft.core.AchievementManager@23405207 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 15: ASM: enviromine.handlers.EM_EventManager@720582e6 onCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 16: ASM: enviromine.handlers.crafting.CamelPackRefillHandler@36c4788d onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 17: ASM: enviromine.handlers.crafting.CamelPackIntegrationHandler@3ce6e6e onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 18: ASM: enviromine.handlers.crafting.GaskMaskRefillHandler@4b07c3c onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 19: ASM: enviromine.handlers.crafting.LampLightingHandler@366baf25 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 20: ASM: thaumic.tinkerer.common.item.SpellClothCraftingHandler@4b8eef1f ItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 21: ASM: fox.spiteful.forbidden.FMEventHandler@26474176 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 22: ASM: galaxyspace.SolarSystem.core.achievements.AchEvent@6f3a9711 onCraft(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 23: ASM: com.jaquadro.minecraft.gardentrees.core.handlers.ForgeEventHandler@68eeb408 handleCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 24: ASM: blusunrize.immersiveengineering.common.EventHandler@1b9a4099 onItemCrafted(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 25: ASM: li.cil.oc.common.EventHandler$@6347d2d1 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 26: ASM: mcjty.rftools.FMLEventHandlers@7552cacc onItemCraftedEvent(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 27: ASM: com.draco18s.ores.OresEventHandler@28c793d1 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/ERROR] [FML/]: 28: ASM: com.draco18s.wildlife.WildlifeEventHandler@77565456 onCrafting(Lcpw/mods/fml/common/gameevent/PlayerEvent$ItemCraftedEvent;)V
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at hardcorequesting.quests.QuestTaskItemsCrafting.create(QuestTaskItemsCrafting.java:36)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at hardcorequesting.quests.QuestTaskItemsCrafting.onCrafting(QuestTaskItemsCrafting.java:32)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at hardcorequesting.EventHandler.onEvent(EventHandler.java:80)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler_145_EventHandler_onEvent_ItemCraftedEvent.invoke(.dynamic)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at cpw.mods.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:570)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onCrafted(UnitCrafting.java:108)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onCrafting(UnitCrafting.java:91)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onProduction(UnitCrafting.java:524)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.page.unit.Unit.produce(Unit.java:154)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.page.unit.Unit.onUpdate(Unit.java:184)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.page.unit.UnitCrafting.onUpdate(UnitCrafting.java:265)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.page.PageMain.onUpdate(PageMain.java:51)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at com.ewyboy.ewysworkshop.tileentity.TileEntityTable.func_145845_h(TileEntityTable.java:320)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.world.World.func_72939_s(World.java:1939)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[14:40:17] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]:        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
`

**Comment by Haggle1996** [comment]
It looks like multiple machines (I see both Ewy's and AE2 in the snippet) are set to autocraft something that is no longer valid.

**Comment by devanchya** [comment]
thanks haggle

**Comment by devanchya** [comment]
it is a Wooden Pickaxe being automated through the Ewy's Table.  This is being used to make a wooden pickaxe attached to a the Ender IO farming station to cut down trees to make coal for a steamer.

The item being made is minecraft:wooden_axe and it is enabled and not disabled.   Bug in Ewy's auto-crafting?

**Comment by Haggle1996** [comment]
Thinking about this more, autocrafting in Steve's Workshop (before it became Ewy's) has always been very hard on TPS. On the REV|1 development server we actually had a warning message not to use workshops for autocrafting, as just one table could eat up 10-15ms of the available 50. Maybe this issue was not resolved when Ewy' took it over.

If this is the case, then yes, Ewy's has a bug. Out of question, if you break the table and just put a bedrock axe in the farming station for now, does it improve the lag?

**Comment by devanchya** [comment]
I've done some testing and this appears to be a bug with Ewy's autocrafting.  Even happens with valid recipes.  Take out the auto-upgrade and it fixes itself.

**Comment by devanchya** [comment]
Switching to a Bedrock Axe fixes the issue, so it's confirmed it is a Ewy's autocrafting issue.

**Comment by devanchya** [comment]
Charcoal to Charcoal Block also caused the error, it appears to be any auto crafting with Ewy
