### ISSUE TITLE
NEI/ChromatiCraft: Crash when cycling through the recipes for the Coalescence Orchid

### ISSUE THREAD

**Issue by Ieldra2** [Haggle1996/RevolutionPack#381]
The Coalescence Orchid can be crafted with many different flowers and leaves. One or more of them cause a crash as NEI cycles through the available options.

Crash log excerpt:

Description: Rendering item

java.lang.ArrayIndexOutOfBoundsException: 3
    at mods.natura.blocks.trees.NLeaves.func_149691_a(NLeaves.java:159)
    at net.minecraft.client.renderer.RenderBlocks.func_147787_a(RenderBlocks.java:9366)
    at net.minecraft.client.renderer.RenderBlocks.func_147800_a(RenderBlocks.java:9278)
    at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:446)
    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
    at Reika.DragonAPI.Libraries.IO.ReikaGuiAPI.drawItemStack(ReikaGuiAPI.java:446)
    at Reika.DragonAPI.Libraries.IO.ReikaGuiAPI.drawItemStackWithTooltip(ReikaGuiAPI.java:464)
    at Reika.ChromatiCraft.Auxiliary.ChromaBookData.drawCastingRecipe(ChromaBookData.java:76)
    at Reika.ChromatiCraft.GUI.Book.GuiCastingRecipe.drawAuxData(GuiCastingRecipe.java:158)
    at Reika.ChromatiCraft.GUI.Book.GuiCastingRecipe.drawRecipes(GuiCastingRecipe.java:151)
    at Reika.ChromatiCraft.GUI.Book.GuiCastingRecipe.func_73863_a(GuiCastingRecipe.java:227)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1397)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Haggle1996** [comment]
I can't replicate this, but may be fixed in the next update due to reenabling Reika's null-stack cleanup.

**Comment by ReikaKalseki** [comment]
This is not a null stack but an invalid one.
