### ISSUE TITLE
crash while looking at "Aspect" on the thaumonomicon

### ISSUE THREAD

**Issue by DorinnB** [Haggle1996/RevolutionPack#446]
`[23:23:02] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1654) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.StackOverflowError
    at java.util.LinkedHashMap.afterNodeInsertion(Unknown Source) ~[?:1.8.0_91]
    at java.util.HashMap.putVal(Unknown Source) ~[?:1.8.0_91]
    at java.util.HashMap.put(Unknown Source) ~[?:1.8.0_91]
    at thaumcraft.api.aspects.AspectList.add(AspectList.java:196) ~[AspectList.class:?]
    at thaumcraft.api.aspects.AspectList.copy(AspectList.java:36) ~[AspectList.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:567) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:576) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:576) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:576) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:891) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551) ~[ThaumcraftCraftingManager.class:?]
    at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525) ~[ThaumcraftCraftingManager.class:?]`

**Comment by DorinnB** [comment]
fix : Setting B:"Enable transmutations" to false in the WitchingGadgets

source : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2371563-thaumcraft-addon-witching-gadgets

**Comment by Haggle1996** [comment]
Fixed in the next update.

**Comment by Haggle1996** [comment]
By the way, thank you very much for including the fix as well as the issue report. :D

**Comment by mcdodge34** [comment]
Hope it won't cause the issue to be opened again, just to say thanks, I had this weird problem if I tried to look at my aspects in my thaumonomicon or if for whatever reason I tried to put a HV cable connector from Immersive engineering in any inventory, chest, ae2 network, backpack, it would kick me out of the game, I'm playing FTB Infinity Evolved Skyblock and it happens that we also added Witching gadgets to the pack because of various utilities like the abbacus to check infusion altar stability ranking. Setting the config to false solved the issue
