### ISSUE TITLE
New Chromaticraft Gem Crash

### ISSUE THREAD

**Issue by devanchya** [Haggle1996/RevolutionPack#455]
Put the new Gem in your hand, your CTD.  Reika acknowledged issue on #revolution chat.   Said it is patched in 14d already.

`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/8/16 11:13 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at Reika.ChromatiCraft.Base.ItemChromaBasic.obfuscateIf(ItemChromaBasic.java:165)
    at Reika.ChromatiCraft.Base.ItemChromaBasic.obfuscate(ItemChromaBasic.java:138)
    at Reika.ChromatiCraft.Base.ItemChromaBasic.func_77653_i(ItemChromaBasic.java:120)
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
    at net.minecraftforge.client.GuiIngameForge.renderToolHightlight(GuiIngameForge.java:583)
    at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:154)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1362)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

`

**Comment by Kreidos** [comment]
So, we're posting this to remind Haggle to update to 14d?

**Comment by Haggle1996** [comment]
I think he posted it just to make sure players are aware it's a known issue until the update; and to make haggle aware of it.

**Comment by Haggle1996** [comment]
Fixed in the next update.
