### ISSUE TITLE
After upgrading to 3.1.0, RotaryCraft clutches spam NPE messages in the chat interface.

### ISSUE THREAD

**Issue by Ieldra2** [Haggle1996/RevolutionPack#496]
Here's the error message:

[22:20:14] [Client thread/INFO] [FML/]: DRAGONAPI: 
[22:20:14] [Client thread/ERROR] [FML/]: DRAGONAPI ERROR: Tile Entity Clutch @ DIM0: 3919, 73, 4429 [CLIENT] is throwing class java.lang.NullPointerException on update: null
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.RotaryCraft.Registry.MachineRegistry.getMachine(MachineRegistry.java:493)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.RotaryCraft.TileEntities.Transmission.TileEntityClutch.transferPower(TileEntityClutch.java:49)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.RotaryCraft.TileEntities.Transmission.TileEntityClutch.transferPower(TileEntityClutch.java:100)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.RotaryCraft.TileEntities.Transmission.TileEntityClutch.updateEntity(TileEntityClutch.java:36)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:465)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.world.World.func_72939_s(World.java:1939)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.client.main.Main.main(SourceFile:148)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at java.lang.reflect.Method.invoke(Unknown Source)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[22:20:14] [Client thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

The chat interface is unusable and I don't get any test message from items, so I really can't play 3.1.0 until that problem is resolved. This is a client-only message.

**Comment by Ieldra2** [comment]
OK, already resolved. Apparently this happens when you connect a clutch directly to a world rift.
