### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by GetScaredLittle** [Haggle1996/RevolutionPack#660]
im new to this and have no idea how this works but ive come across a issue installing this pack with atlauncher and I think its because the journey map mod is deleted
heres the log:
### [09/8/2017 13:25:37 PM] Console Cleared
[09/8/2017 13:25:42 PM] Started install of Revolution - 1.5.0.1 (1.7.10)
[09/8/2017 13:26:04 PM] java.io.IOException: http://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download returned response code 404 with message of Not Found

	at com.atlauncher.data.Downloadable.getConnection(Downloadable.java:268)

	at com.atlauncher.data.Downloadable.getFilesize(Downloadable.java:138)

	at com.atlauncher.data.json.Mod.downloadClient(Mod.java:463)

	at com.atlauncher.data.json.Mod.download(Mod.java:333)

	at com.atlauncher.data.json.Mod.download(Mod.java:326)

	at com.atlauncher.workers.InstanceInstaller.downloadMods(InstanceInstaller.java:634)

	at com.atlauncher.workers.InstanceInstaller.installUsingJSON(InstanceInstaller.java:1247)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:1337)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:74)

	at javax.swing.SwingWorker$1.call(Unknown Source)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at javax.swing.SwingWorker.run(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

[09/8/2017 13:26:04 PM] java.io.IOException: http://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download returned response code 404 with message of Not Found

	at com.atlauncher.data.Downloadable.getConnection(Downloadable.java:268)

	at com.atlauncher.data.Downloadable.isGziped(Downloadable.java:207)

	at com.atlauncher.data.Downloadable.downloadFile(Downloadable.java:302)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:439)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:378)

	at com.atlauncher.data.json.Mod.downloadClient(Mod.java:464)

	at com.atlauncher.data.json.Mod.download(Mod.java:333)

	at com.atlauncher.data.json.Mod.download(Mod.java:326)

	at com.atlauncher.workers.InstanceInstaller.downloadMods(InstanceInstaller.java:634)

	at com.atlauncher.workers.InstanceInstaller.installUsingJSON(InstanceInstaller.java:1247)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:1337)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:74)

	at javax.swing.SwingWorker$1.call(Unknown Source)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at javax.swing.SwingWorker.run(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

[09/8/2017 13:26:04 PM] Failed to download http://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download due to IOException!
[09/8/2017 13:26:04 PM] java.io.FileNotFoundException: https://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download

	at sun.reflect.GeneratedConstructorAccessor64.newInstance(Unknown Source)

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

	at java.lang.reflect.Constructor.newInstance(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)

	at java.security.AccessController.doPrivileged(Native Method)

	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)

	at com.atlauncher.data.Downloadable.downloadFile(Downloadable.java:303)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:439)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:378)

	at com.atlauncher.data.json.Mod.downloadClient(Mod.java:464)

	at com.atlauncher.data.json.Mod.download(Mod.java:333)

	at com.atlauncher.data.json.Mod.download(Mod.java:326)

	at com.atlauncher.workers.InstanceInstaller.downloadMods(InstanceInstaller.java:634)

	at com.atlauncher.workers.InstanceInstaller.installUsingJSON(InstanceInstaller.java:1247)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:1337)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:74)

	at javax.swing.SwingWorker$1.call(Unknown Source)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at javax.swing.SwingWorker.run(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

Caused by: java.io.FileNotFoundException: https://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

	at java.net.HttpURLConnection.getResponseCode(Unknown Source)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)

	at com.atlauncher.data.Downloadable.getConnection(Downloadable.java:250)

	at com.atlauncher.data.Downloadable.isGziped(Downloadable.java:207)

	at com.atlauncher.data.Downloadable.downloadFile(Downloadable.java:302)

	... 15 more

[09/8/2017 13:26:04 PM] java.io.IOException: http://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download returned response code 404 with message of Not Found

	at com.atlauncher.data.Downloadable.getConnection(Downloadable.java:268)

	at com.atlauncher.data.Downloadable.isGziped(Downloadable.java:207)

	at com.atlauncher.data.Downloadable.downloadFile(Downloadable.java:302)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:439)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:378)

	at com.atlauncher.data.json.Mod.downloadClient(Mod.java:464)

	at com.atlauncher.data.json.Mod.download(Mod.java:333)

	at com.atlauncher.data.json.Mod.download(Mod.java:326)

	at com.atlauncher.workers.InstanceInstaller.downloadMods(InstanceInstaller.java:634)

	at com.atlauncher.workers.InstanceInstaller.installUsingJSON(InstanceInstaller.java:1247)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:1337)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:74)

	at javax.swing.SwingWorker$1.call(Unknown Source)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at javax.swing.SwingWorker.run(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

[09/8/2017 13:26:04 PM] Failed to download http://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download due to IOException!
[09/8/2017 13:26:04 PM] java.io.FileNotFoundException: https://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download

	at sun.reflect.GeneratedConstructorAccessor64.newInstance(Unknown Source)

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

	at java.lang.reflect.Constructor.newInstance(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)

	at java.security.AccessController.doPrivileged(Native Method)

	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)

	at com.atlauncher.data.Downloadable.downloadFile(Downloadable.java:303)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:439)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:378)

	at com.atlauncher.data.json.Mod.downloadClient(Mod.java:464)

	at com.atlauncher.data.json.Mod.download(Mod.java:333)

	at com.atlauncher.data.json.Mod.download(Mod.java:326)

	at com.atlauncher.workers.InstanceInstaller.downloadMods(InstanceInstaller.java:634)

	at com.atlauncher.workers.InstanceInstaller.installUsingJSON(InstanceInstaller.java:1247)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:1337)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:74)

	at javax.swing.SwingWorker$1.call(Unknown Source)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at javax.swing.SwingWorker.run(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

Caused by: java.io.FileNotFoundException: https://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

	at java.net.HttpURLConnection.getResponseCode(Unknown Source)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)

	at com.atlauncher.data.Downloadable.getConnection(Downloadable.java:250)

	at com.atlauncher.data.Downloadable.isGziped(Downloadable.java:207)

	at com.atlauncher.data.Downloadable.downloadFile(Downloadable.java:302)

	... 15 more

[09/8/2017 13:26:05 PM] java.io.IOException: http://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download returned response code 404 with message of Not Found

	at com.atlauncher.data.Downloadable.getConnection(Downloadable.java:268)

	at com.atlauncher.data.Downloadable.isGziped(Downloadable.java:207)

	at com.atlauncher.data.Downloadable.downloadFile(Downloadable.java:302)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:439)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:378)

	at com.atlauncher.data.json.Mod.downloadClient(Mod.java:464)

	at com.atlauncher.data.json.Mod.download(Mod.java:333)

	at com.atlauncher.data.json.Mod.download(Mod.java:326)

	at com.atlauncher.workers.InstanceInstaller.downloadMods(InstanceInstaller.java:634)

	at com.atlauncher.workers.InstanceInstaller.installUsingJSON(InstanceInstaller.java:1247)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:1337)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:74)

	at javax.swing.SwingWorker$1.call(Unknown Source)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at javax.swing.SwingWorker.run(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

[09/8/2017 13:26:05 PM] Failed to download http://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download due to IOException!
[09/8/2017 13:26:05 PM] java.io.FileNotFoundException: https://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download

	at sun.reflect.GeneratedConstructorAccessor64.newInstance(Unknown Source)

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

	at java.lang.reflect.Constructor.newInstance(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)

	at java.security.AccessController.doPrivileged(Native Method)

	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)

	at com.atlauncher.data.Downloadable.downloadFile(Downloadable.java:303)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:439)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:378)

	at com.atlauncher.data.json.Mod.downloadClient(Mod.java:464)

	at com.atlauncher.data.json.Mod.download(Mod.java:333)

	at com.atlauncher.data.json.Mod.download(Mod.java:326)

	at com.atlauncher.workers.InstanceInstaller.downloadMods(InstanceInstaller.java:634)

	at com.atlauncher.workers.InstanceInstaller.installUsingJSON(InstanceInstaller.java:1247)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:1337)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:74)

	at javax.swing.SwingWorker$1.call(Unknown Source)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at javax.swing.SwingWorker.run(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

Caused by: java.io.FileNotFoundException: https://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

	at java.net.HttpURLConnection.getResponseCode(Unknown Source)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)

	at com.atlauncher.data.Downloadable.getConnection(Downloadable.java:250)

	at com.atlauncher.data.Downloadable.isGziped(Downloadable.java:207)

	at com.atlauncher.data.Downloadable.downloadFile(Downloadable.java:302)

	... 15 more

[09/8/2017 13:26:06 PM] java.io.IOException: http://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download returned response code 404 with message of Not Found

	at com.atlauncher.data.Downloadable.getConnection(Downloadable.java:268)

	at com.atlauncher.data.Downloadable.isGziped(Downloadable.java:207)

	at com.atlauncher.data.Downloadable.downloadFile(Downloadable.java:302)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:439)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:378)

	at com.atlauncher.data.json.Mod.downloadClient(Mod.java:464)

	at com.atlauncher.data.json.Mod.download(Mod.java:333)

	at com.atlauncher.data.json.Mod.download(Mod.java:326)

	at com.atlauncher.workers.InstanceInstaller.downloadMods(InstanceInstaller.java:634)

	at com.atlauncher.workers.InstanceInstaller.installUsingJSON(InstanceInstaller.java:1247)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:1337)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:74)

	at javax.swing.SwingWorker$1.call(Unknown Source)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at javax.swing.SwingWorker.run(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

[09/8/2017 13:26:06 PM] Failed to download http://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download due to IOException!
[09/8/2017 13:26:06 PM] java.io.FileNotFoundException: https://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download

	at sun.reflect.GeneratedConstructorAccessor64.newInstance(Unknown Source)

	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)

	at java.lang.reflect.Constructor.newInstance(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)

	at java.security.AccessController.doPrivileged(Native Method)

	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)

	at com.atlauncher.data.Downloadable.downloadFile(Downloadable.java:303)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:439)

	at com.atlauncher.data.Downloadable.download(Downloadable.java:378)

	at com.atlauncher.data.json.Mod.downloadClient(Mod.java:464)

	at com.atlauncher.data.json.Mod.download(Mod.java:333)

	at com.atlauncher.data.json.Mod.download(Mod.java:326)

	at com.atlauncher.workers.InstanceInstaller.downloadMods(InstanceInstaller.java:634)

	at com.atlauncher.workers.InstanceInstaller.installUsingJSON(InstanceInstaller.java:1247)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:1337)

	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:74)

	at javax.swing.SwingWorker$1.call(Unknown Source)

	at java.util.concurrent.FutureTask.run(Unknown Source)

	at javax.swing.SwingWorker.run(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.lang.Thread.run(Unknown Source)

Caused by: java.io.FileNotFoundException: https://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

	at java.net.HttpURLConnection.getResponseCode(Unknown Source)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)

	at com.atlauncher.data.Downloadable.getConnection(Downloadable.java:250)

	at com.atlauncher.data.Downloadable.isGziped(Downloadable.java:207)

	at com.atlauncher.data.Downloadable.downloadFile(Downloadable.java:302)

	... 15 more

[09/8/2017 13:26:06 PM] File **USERSDIR**\Downloads\journeymap-1.7.10-5.1.4p1-unlimited.jar cannot be copied to **USERSDIR**\FailedDownloads as it isn't a file
[09/8/2017 13:26:06 PM] File **USERSDIR**\Downloads\journeymap-1.7.10-5.1.4p1-unlimited.jar cannot be copied to **USERSDIR**\FailedDownloads as it doesn't exist
[09/8/2017 13:26:06 PM] Error downloading journeymap-1.7.10-5.1.4p1-unlimited.jar from http://minecraft.curseforge.com/projects/journeymap-32274/files/2296716/download. Expected hash of 9091571243da9b1532ba2d8fef3f2eea but got 0 instead. Copied to FailedDownloads Folder. Cancelling install!
[09/8/2017 13:26:06 PM] Cannot get MD5 of **USERSDIR**\Downloads\journeymap-1.7.10-5.1.4p1-unlimited.jar as it doesn't exist

**Comment by Haggle1996** [comment]
I updated the URL for JourneyMap. You should be able to download the pack again. Thanks for reporting.
