### ISSUE TITLE
 Failed to prepare instance Revolution for launch. Check the logs and try again.

### ISSUE THREAD

**Issue by nerdydude94** [Haggle1996/RevolutionPack#667]
it was working on the 15/01/21 today on the 16/01/21 its not loading or letting me download it again 

anyway to get it working again?

**Comment by Haggle1996** [comment]
This is an AT Launcher issue, not a problem with the pack. Do you have a log file to post?

**Comment by nerdydude94** [comment]
12:51:23.733 [ATL-Logging-Thread] INFO  - Organising filesystem

12:51:24.273 [ATL-Logging-Thread] INFO  - ATLauncher Version: 3.4.2.6

12:51:24.275 [ATL-Logging-Thread] INFO  - Java Version: Launcher: Java 8
(1.8.0_271), Minecraft: Java 8 (1.8.0_271)

12:51:24.278 [ATL-Logging-Thread] INFO  - Java Path: C:\Program
Files\Java\jre1.8.0_271

12:51:24.279 [ATL-Logging-Thread] INFO  - 64 Bit Java: true

12:51:24.280 [ATL-Logging-Thread] INFO  - RAM Available: 32681MB

12:51:24.280 [ATL-Logging-Thread] INFO  - Launcher Directory: **USERSDIR**

12:51:24.413 [ATL-Logging-Thread] INFO  - GPU: NVIDIA GeForce GTX 1080
(NVIDIA (0x10de)) DriverVersion=27.21.14.6089 4095MB VRAM

12:51:24.429 [ATL-Logging-Thread] INFO  - CPU: 10 cores/20 threads

12:51:24.455 [ATL-Logging-Thread] INFO  - Operating System: Windows (10.0
(Home) build 18363)

12:51:24.456 [ATL-Logging-Thread] INFO  - Bitness: 64

12:51:24.456 [ATL-Logging-Thread] INFO  - Uptime: 762838

12:51:24.457 [ATL-Logging-Thread] INFO  - Manufacturer: Microsoft

12:51:24.484 [ATL-Logging-Thread] INFO  - Disk: Acer (529716 MB Free)

12:51:24.485 [ATL-Logging-Thread] INFO  - Disk: System Reserved (463 MB
Free)

12:51:24.485 [ATL-Logging-Thread] INFO  - Disk:  (1387135 MB Free)

12:51:24.487 [ATL-Logging-Thread] INFO  - Showing splash screen and loading
everything

12:51:24.488 [ATL-Logging-Thread] INFO  - Checking for updated files!

12:51:48.894 [ATL-Logging-Thread] INFO  - Launcher finished loading
everything

12:52:08.796 [ATL-Logging-Thread] INFO  - Launcher opening

12:52:08.796 [ATL-Logging-Thread] INFO  - Made By Bob*

12:52:08.796 [ATL-Logging-Thread] INFO  - *(Not Actually)

12:52:09.060 [ATL-Logging-Thread] INFO  - Setting up Bottom Bar

12:52:14.784 [ATL-Logging-Thread] INFO  - Finished Setting up Bottom Bar

12:52:14.784 [ATL-Logging-Thread] INFO  - Setting up Tabs

12:52:23.671 [ATL-Logging-Thread] INFO  - Finished Setting up Tabs

12:52:23.672 [ATL-Logging-Thread] INFO  - Showing Launcher

12:53:43.977 [ATL-Logging-Thread] INFO  - Started install of Revolution
version 1.5.0.1

12:55:35.178 [ATL-Logging-Thread] ERROR - Error trying to download
journeymap-1.7.10-5.1.4p1-unlimited.jar

12:55:35.183 [ATL-Logging-Thread] ERROR -
com.atlauncher.network.DownloadException:
https://www.curseforge.com/minecraft/mc-mods/ourneymap-32274/download/2296716/file
request wasn't successful: Response{protocol=h2, code=403, message=, url=
https://www.curseforge.com/minecraft/mc-mods/ourneymap-32274/download/2296716/file
}
at com.atlauncher.network.Download.execute(Download.java:293)
at com.atlauncher.network.Download.downloadFile(Download.java:546)
at com.atlauncher.network.DownloadPool$Downloader.run(DownloadPool.java:122)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

12:55:53.342 [ATL-Logging-Thread] INFO  - Log uploaded and link copied to
clipboard: https://paste.atlauncher.com/view/c52fcdd0

**Comment by nerdydude94** [comment]
this is what happens when its downloaded

[24/01/2021 13:08:50 PM] Organising filesystem
[24/01/2021 13:08:50 PM] ATLauncher Version: 3.4.2.6
[24/01/2021 13:08:50 PM] Java Version: Launcher: Java 8 (1.8.0_271),
Minecraft: Java 8 (1.8.0_271)
[24/01/2021 13:08:50 PM] Java Path: C:\Program Files\Java\jre1.8.0_271
[24/01/2021 13:08:50 PM] 64 Bit Java: true
[24/01/2021 13:08:50 PM] RAM Available: 32681MB
[24/01/2021 13:08:50 PM] Launcher Directory: **USERSDIR**
[24/01/2021 13:08:51 PM] GPU: NVIDIA GeForce GTX 1080 (NVIDIA (0x10de))
DriverVersion=27.21.14.6089 4095MB VRAM
[24/01/2021 13:08:51 PM] CPU: 10 cores/20 threads
[24/01/2021 13:08:51 PM] Operating System: Windows (10.0 (Home) build 18363)
[24/01/2021 13:08:51 PM] Bitness: 64
[24/01/2021 13:08:51 PM] Uptime: 763885
[24/01/2021 13:08:51 PM] Manufacturer: Microsoft
[24/01/2021 13:08:51 PM] Disk: Acer (529737 MB Free)
[24/01/2021 13:08:51 PM] Disk: System Reserved (463 MB Free)
[24/01/2021 13:08:51 PM] Disk:  (1387135 MB Free)
[24/01/2021 13:08:51 PM] Showing splash screen and loading everything
[24/01/2021 13:08:51 PM] Checking for updated files!
[24/01/2021 13:08:52 PM] Launcher finished loading everything
[24/01/2021 13:08:52 PM] Launcher opening
[24/01/2021 13:08:52 PM] Made By Bob*
[24/01/2021 13:08:52 PM] *(Not Actually)
[24/01/2021 13:08:52 PM] Setting up Bottom Bar
[24/01/2021 13:08:52 PM] Finished Setting up Bottom Bar
[24/01/2021 13:08:52 PM] Setting up Tabs
[24/01/2021 13:08:52 PM] Finished Setting up Tabs
[24/01/2021 13:08:52 PM] Showing Launcher
[24/01/2021 13:08:56 PM] Preparing for launch!
[24/01/2021 13:08:56 PM] Launching pack Revolution 1.5.0.1 for Minecraft
1.7.10
[24/01/2021 13:08:56 PM] Logging into Minecraft!
[24/01/2021 13:08:57 PM] Trying to login with access token!
[24/01/2021 13:08:57 PM] Launching Minecraft with the following arguments
(user related stuff has been removed): [C:\Program
Files\Java\jre1.8.0_271\bin\javaw, -XX:-OmitStackTraceInFastThrow,
-Xms4096M, -Xmx11264M, -XX:MetaspaceSize=256M, -Duser.language=en,
-Duser.country=US, -Dfml.log.level=INFO, -XX:+UnlockExperimentalVMOptions,
-XX:+UseG1GC, -XX:G1NewSizePercent=20, -XX:G1ReservePercent=20,
-XX:MaxGCPauseMillis=50, -XX:G1HeapRegionSize=32M,
-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump,
-Djava.library.path=USERSDIR\temp\natives-85ae7a84c69c4bc292357d7345be682e,
-cp,
USERSDIR\libraries\net\minecraft\client\1.7.10\client-1.7.10.jar;USERSDIR\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar;USERSDIR\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar;USERSDIR\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar;USERSDIR\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar;USERSDIR\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar;USERSDIR\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar;USERSDIR\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar;USERSDIR\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar;USERSDIR\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar;USERSDIR\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar;USERSDIR\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar;USERSDIR\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar;USERSDIR\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar;USERSDIR\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar;USERSDIR\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar;USERSDIR\libraries\com\google\guava\guava\17.0\guava-17.0.jar;USERSDIR\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;USERSDIR\libraries\com\mojang\netty\1.6\netty-1.6.jar;USERSDIR\libraries\com\mojang\realms\1.3.5\realms-1.3.5.jar;USERSDIR\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;USERSDIR\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;USERSDIR\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;USERSDIR\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;USERSDIR\libraries\java3d\vecmath\1.3.1\vecmath-1.3.1.jar;USERSDIR\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;USERSDIR\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;USERSDIR\libraries\net\sf\jopt-simple\jopt-simple\4.5\jopt-simple-4.5.jar;USERSDIR\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;USERSDIR\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;USERSDIR\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;USERSDIR\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;USERSDIR\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;USERSDIR\libraries\io\netty\netty-all\4.0.10.Final\netty-all-4.0.10.Final.jar;USERSDIR\libraries\com\google\guava\guava\15.0\guava-15.0.jar;USERSDIR\libraries\org\apache\commons\commons-lang3\3.1\commons-lang3-3.1.jar;USERSDIR\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar;USERSDIR\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;USERSDIR\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;USERSDIR\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;USERSDIR\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;USERSDIR\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar;USERSDIR\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;USERSDIR\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;USERSDIR\libraries\org\lwjgl\lwjgl\lwjgl\2.9.1\lwjgl-2.9.1.jar;USERSDIR\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.1\lwjgl_util-2.9.1.jar;USERSDIR\libraries\tv\twitch\twitch\5.16\twitch-5.16.jar;USERSDIR\libraries\org\lwjgl\lwjgl\lwjgl-platform\2.9.1\lwjgl-platform-2.9.1-natives-windows.jar;USERSDIR\libraries\net\java\jinput\jinput-platform\2.0.5\jinput-platform-2.0.5-natives-windows.jar;USERSDIR\libraries\tv\twitch\twitch-platform\5.16\twitch-platform-5.16-natives-windows-64.jar;USERSDIR\libraries\tv\twitch\twitch-external-platform\4.5\twitch-external-platform-4.5-natives-windows-64.jar,
net.minecraft.launchwrapper.Launch, --username, REDACTED, --version,
1.7.10, --gameDir, USERSDIR\instances\Revolution, --assetsDir,
USERSDIR\assets, --assetIndex, 1.7.10, --uuid,
273bd94c41a542f6a435586afb47032b, --accessToken, REDACTED,
--userProperties, REDACTED, --userType, mojang,
--tweakClass=cpw.mods.fml.common.launcher.FMLTweaker, --width=854,
--height=480]
[24/01/2021 13:08:59 PM] [main/INFO]: Loading tweak class name
cpw.mods.fml.common.launcher.FMLTweaker
[24/01/2021 13:09:00 PM] [main/ERROR]: Unable to launch
[24/01/2021 13:09:00 PM] java.lang.ClassNotFoundException:
cpw.mods.fml.common.launcher.FMLTweaker
[24/01/2021 13:09:00 PM] at java.net.URLClassLoader.findClass(Unknown
Source) ~[?:1.8.0_271]
[24/01/2021 13:09:00 PM] at java.lang.ClassLoader.loadClass(Unknown Source)
~[?:1.8.0_271]
[24/01/2021 13:09:00 PM] at
sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
[24/01/2021 13:09:00 PM] at java.lang.ClassLoader.loadClass(Unknown Source)
~[?:1.8.0_271]
[24/01/2021 13:09:00 PM] at
net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
~[launchwrapper-1.12.jar:?]
[24/01/2021 13:09:00 PM] at java.lang.ClassLoader.loadClass(Unknown Source)
~[?:1.8.0_271]
[24/01/2021 13:09:00 PM] at java.lang.ClassLoader.loadClass(Unknown Source)
~[?:1.8.0_271]
[24/01/2021 13:09:00 PM] at java.lang.Class.forName0(Native Method)
~[?:1.8.0_271]
[24/01/2021 13:09:00 PM] at java.lang.Class.forName(Unknown Source)
~[?:1.8.0_271]
[24/01/2021 13:09:00 PM] at
net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[launchwrapper-1.12.jar:?]
[24/01/2021 13:09:00 PM] at
net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[launchwrapper-1.12.jar:?]
[24/01/2021 13:09:00 PM] Oh no. Minecraft crashed. Please check the logs
for any errors and provide these logs when asking for support.
[24/01/2021 13:09:00 PM] Checking for modifications to the pack since
installation.
[24/01/2021 13:09:00 PM] The mod journeymap-1.7.10-5.1.4p2-unlimited.jar
has been added.
[24/01/2021 13:09:00 PM] The mod VeinMiner-1.7.10_0.27.0.unknown.jar has
been added.
[24/01/2021 13:09:00 PM] Checking for updated files!
