### ISSUE TITLE
Breaking charged Reactorcraft Toroid Magnet gives error on Revolution 1.0.10.0

### ISSUE THREAD

**Issue by DarLeroux** [Haggle1996/RevolutionPack#87]
I accidentally broke a toroid magnet that had some charge in it while trying to fix the plasma injector facing, and immediately got the following error. It kept repeating until I logged out, and even after shutting down MC completely and coming back in still getting issue. 

[03/9/2015 19:12:24 PM] [19:12:23] [Client thread/INFO]: [CHAT] Tile Entity Toroid Magnet @ DIM0: 2, 56, 235 is throwing class java.lang.ClassCastException on update: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to Reika.ReactorCraft.TileEntities.Fusion.TileEntityToroidMagnet
[03/9/2015 19:12:24 PM] [Client thread/INFO]: [CHAT] [Reika.ReactorCraft.TileEntities.Fusion.TileEntityToroidMagnet.distributeCharge(TileEntityToroidMagnet.java:227), Reika.ReactorCraft.TileEntities.Fusion.TileEntityToroidMagnet.updateEntity(TileEntityToroidMagnet.java:120), Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:428), net.minecraft.world.World.func_72939_s(World.java:1939), net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006), net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973), net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898), net.minecraft.client.main.Main.main(SourceFile:148), sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method), sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source), sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source), java.lang.reflect.Method.invoke(Unknown Source), net.minecraft.launchwrapper.Launch.launch(Launch.java:135), net.minecraft.launchwrapper.Launch.main(Launch.java:28)]
[03/9/2015 19:12:24 PM] [Client thread/INFO]: [CHAT] 
[03/9/2015 19:12:24 PM] [19:12:23] [Client thread/INFO] [FML]: Tile Entity Toroid Magnet @ DIM0: 2, 56, 235 is throwing class java.lang.ClassCastException on update: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to Reika.ReactorCraft.TileEntities.Fusion.TileEntityToroidMagnet
[03/9/2015 19:12:24 PM] [19:12:23] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.ClassCastException: mods.railcraft.common.blocks.hidden.TileHidden cannot be cast to Reika.ReactorCraft.TileEntities.Fusion.TileEntityToroidMagnet
[03/9/2015 19:12:24 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.ReactorCraft.TileEntities.Fusion.TileEntityToroidMagnet.distributeCharge(TileEntityToroidMagnet.java:227)
[03/9/2015 19:12:24 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.ReactorCraft.TileEntities.Fusion.TileEntityToroidMagnet.updateEntity(TileEntityToroidMagnet.java:120)
[03/9/2015 19:12:24 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:428)
[03/9/2015 19:12:24 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.world.World.func_72939_s(World.java:1939)
[03/9/2015 19:12:24 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
[03/9/2015 19:12:24 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[03/9/2015 19:12:24 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[03/9/2015 19:12:24 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[03/9/2015 19:12:24 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03/9/2015 19:12:24 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[03/9/2015 19:12:24 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[03/9/2015 19:12:24 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[03/9/2015 19:12:24 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[03/9/2015 19:12:24 PM] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[03/9/2015 19:12:24 PM] [Client thread/INFO] [FML]:

**Comment by Haggle1996** [comment]
Try setting B:residual.heat=false in your config/railcraft/blocks.cfg and reload the save. I don't know if you're able to play with it spamming the console, but replacing the block should also fix it.

Until we're on the latest version of v8 from Reika and can retest the issue, a bug report to him won't produce anything useful. Let me know if you're able to fix it with the above steps.

**Comment by DarLeroux** [comment]
Ok that worked, not getting the error anymore, and was able to replace block. Thanks for your quick response!
